apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: container1
    image: public.ecr.aws/docker/library/alpine
    command: ["sleep"]
    args:
    - 10h
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data: {}
