apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
---


---
apiVersion: v1
kind: Secret
metadata:
  name: post-delete-secret
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
type: Opaque
data: {}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-delete-job
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: post-delete-container
          image: busybox
          command: ["sh", "-c", "echo 'Post-delete task executed'"]
      restartPolicy: Never
