apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-sleep
  labels:
    app: alpine-sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-sleep
  template:
    metadata:
      labels:
        app: alpine-sleep
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["sleep", "infinity"]

---
apiVersion: v1
kind: Secret
metadata:
  name: post-delete-secret
  annotations:
    argocd.argoproj.io/hook: PostDelete
type: Opaque
data: {}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-delete-job
  annotations:
    argocd.argoproj.io/hook: PostDelete
spec:
  template:
    spec:
      containers:
        - name: post-delete-container
          image: busybox
          command: ["sh", "-c", "echo 'Post-delete task executed'"]
      restartPolicy: Never
