

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: web-app
spec:
  containers:
  - name: web-server
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: log-aggregator
    image: fluent/fluentd:v1.14
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes:
  - name: log-volume
    emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: post-delete-secret
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
type: Opaque
data: {}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-delete-job
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: post-delete-container
          image: busybox
          command: ["sh", "-c", "echo 'Post-delete task executed'"]
      restartPolicy: Never
